[deploy]
bucket = 'mysycry-cfn-artifacts'
region = 'ca-central-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:ca-central-1:211572490796:certificate/e2620a10-ee4c-40d1-9970-d7e86866f75f'

NetworkingStack = 'CrdNet'