[deploy]
bucket = 'mysycry-cfn-artifacts'
region = 'ca-central-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:211572490796:certificate/db77d581-d9d0-4ba6-a2a7-852f491b3edc'
WwwBucketName = 'www.cloudmate.tech'
RootBucketName = 'cloudmate.tech'